services:
  - type: web
    name: your_django_app_name
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_django_app_name.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: ALLOWED_HOSTS
        value: your_django_app_name.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
databases:
  - name: your_database_name
    databaseName: your_database_name
    user: your_database_user