# Generated by Django 5.2.1 on 2025-06-04 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_phone_order_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_review', 'На рассмотрении'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('rejected', 'Отклонён')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ConstructionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('house', 'Жилой дом'), ('garage', 'Гараж'), ('warehouse', 'Склад'), ('other', 'Другое')], max_length=50)),
                ('description', models.TextField()),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_constructions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
